[workspace]
members = ["crates/kit"]
resolver = "2"

[workspace.package]
authors = ["kit-tool"]
repository = "https://github.com/kit-tool/kit"
categories = ["tools"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"
