[workspace]
members = ["crates/kit-tauri", "crates/kit-plugin", "crates/kit-api"]
resolver = "2"

[workspace.dependencies]

kit-plugin = { path = "crates/kit-plugin" }
kit-api = { path = "crates/kit-api" }
