[package]
name = "kit-plugin"
version = "0.1.0"
description = "A Kit Tool"
authors.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
